apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eo0uht8go-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eo0uht8go-python 
  name: eo0uht8go-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eo0uht8go-python 
