apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eo0uht8go-python 
  janus-idp.io/tekton: eo0uht8go-python
  backstage.io/kubernetes-id: eo0uht8go-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eo0uht8go-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml